// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateAndUploadDBBackup() {
  return window['go']['service']['BackupService']['CreateAndUploadDBBackup']();
}

export function CreateBackup(arg1) {
  return window['go']['service']['BackupService']['CreateBackup'](arg1);
}

export function CreateDBBackup() {
  return window['go']['service']['BackupService']['CreateDBBackup']();
}

export function CreateFullDataBackup(arg1) {
  return window['go']['service']['BackupService']['CreateFullDataBackup'](arg1);
}

export function DeleteBackup(arg1) {
  return window['go']['service']['BackupService']['DeleteBackup'](arg1);
}

export function DeleteDBBackup(arg1) {
  return window['go']['service']['BackupService']['DeleteDBBackup'](arg1);
}

export function DownloadCloudBackup(arg1, arg2) {
  return window['go']['service']['BackupService']['DownloadCloudBackup'](arg1, arg2);
}

export function DownloadCloudDBBackup(arg1) {
  return window['go']['service']['BackupService']['DownloadCloudDBBackup'](arg1);
}

export function ExchangeOneDriveCode(arg1) {
  return window['go']['service']['BackupService']['ExchangeOneDriveCode'](arg1);
}

export function GetBackupDir() {
  return window['go']['service']['BackupService']['GetBackupDir']();
}

export function GetCloudBackupStatus() {
  return window['go']['service']['BackupService']['GetCloudBackupStatus']();
}

export function GetCloudDBBackups() {
  return window['go']['service']['BackupService']['GetCloudDBBackups']();
}

export function GetCloudGameBackups(arg1) {
  return window['go']['service']['BackupService']['GetCloudGameBackups'](arg1);
}

export function GetDBBackupDir() {
  return window['go']['service']['BackupService']['GetDBBackupDir']();
}

export function GetDBBackups() {
  return window['go']['service']['BackupService']['GetDBBackups']();
}

export function GetFullBackupDir() {
  return window['go']['service']['BackupService']['GetFullBackupDir']();
}

export function GetGameBackups(arg1) {
  return window['go']['service']['BackupService']['GetGameBackups'](arg1);
}

export function GetOneDriveAuthURL() {
  return window['go']['service']['BackupService']['GetOneDriveAuthURL']();
}

export function Init(arg1, arg2, arg3) {
  return window['go']['service']['BackupService']['Init'](arg1, arg2, arg3);
}

export function OpenBackupFolder(arg1) {
  return window['go']['service']['BackupService']['OpenBackupFolder'](arg1);
}

export function RestoreBackup(arg1) {
  return window['go']['service']['BackupService']['RestoreBackup'](arg1);
}

export function RestoreFromCloud(arg1, arg2) {
  return window['go']['service']['BackupService']['RestoreFromCloud'](arg1, arg2);
}

export function ScheduleDBRestore(arg1) {
  return window['go']['service']['BackupService']['ScheduleDBRestore'](arg1);
}

export function ScheduleDBRestoreFromCloud(arg1) {
  return window['go']['service']['BackupService']['ScheduleDBRestoreFromCloud'](arg1);
}

export function ScheduleFullDataRestore(arg1) {
  return window['go']['service']['BackupService']['ScheduleFullDataRestore'](arg1);
}

export function SelectBackupRestorePath() {
  return window['go']['service']['BackupService']['SelectBackupRestorePath']();
}

export function SelectBackupSavePath() {
  return window['go']['service']['BackupService']['SelectBackupSavePath']();
}

export function SetupCloudBackup(arg1) {
  return window['go']['service']['BackupService']['SetupCloudBackup'](arg1);
}

export function StartOneDriveAuth() {
  return window['go']['service']['BackupService']['StartOneDriveAuth']();
}

export function TestOneDriveConnection(arg1) {
  return window['go']['service']['BackupService']['TestOneDriveConnection'](arg1);
}

export function TestS3Connection(arg1) {
  return window['go']['service']['BackupService']['TestS3Connection'](arg1);
}

export function UploadDBBackupToCloud(arg1) {
  return window['go']['service']['BackupService']['UploadDBBackupToCloud'](arg1);
}

export function UploadGameBackupToCloud(arg1, arg2) {
  return window['go']['service']['BackupService']['UploadGameBackupToCloud'](arg1, arg2);
}
