// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {vo} from '../models';
import {models} from '../models';
import {context} from '../models';
import {sql} from '../models';
import {appconf} from '../models';

export function CreateAndUploadDBBackup():Promise<vo.DBBackupInfo>;

export function CreateBackup(arg1:string):Promise<models.GameBackup>;

export function CreateDBBackup():Promise<vo.DBBackupInfo>;

export function CreateFullDataBackup(arg1:string):Promise<void>;

export function DeleteBackup(arg1:string):Promise<void>;

export function DeleteDBBackup(arg1:string):Promise<void>;

export function DownloadCloudBackup(arg1:string,arg2:string):Promise<string>;

export function DownloadCloudDBBackup(arg1:string):Promise<string>;

export function ExchangeOneDriveCode(arg1:string):Promise<string>;

export function GetBackupDir():Promise<string>;

export function GetCloudBackupStatus():Promise<vo.CloudBackupStatus>;

export function GetCloudDBBackups():Promise<Array<vo.CloudBackupItem>>;

export function GetCloudGameBackups(arg1:string):Promise<Array<vo.CloudBackupItem>>;

export function GetDBBackupDir():Promise<string>;

export function GetDBBackups():Promise<vo.DBBackupStatus>;

export function GetFullBackupDir():Promise<string>;

export function GetGameBackups(arg1:string):Promise<Array<models.GameBackup>>;

export function GetOneDriveAuthURL():Promise<string>;

export function Init(arg1:context.Context,arg2:sql.DB,arg3:appconf.AppConfig):Promise<void>;

export function OpenBackupFolder(arg1:string):Promise<void>;

export function RestoreBackup(arg1:string):Promise<void>;

export function RestoreFromCloud(arg1:string,arg2:string):Promise<void>;

export function ScheduleDBRestore(arg1:string):Promise<void>;

export function ScheduleDBRestoreFromCloud(arg1:string):Promise<void>;

export function ScheduleFullDataRestore(arg1:string):Promise<void>;

export function SelectBackupRestorePath():Promise<string>;

export function SelectBackupSavePath():Promise<string>;

export function SetupCloudBackup(arg1:string):Promise<string>;

export function StartOneDriveAuth():Promise<string>;

export function TestOneDriveConnection(arg1:appconf.AppConfig):Promise<void>;

export function TestS3Connection(arg1:appconf.AppConfig):Promise<void>;

export function UploadDBBackupToCloud(arg1:string):Promise<void>;

export function UploadGameBackupToCloud(arg1:string,arg2:string):Promise<void>;
