// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddCategory(arg1) {
  return window['go']['service']['CategoryService']['AddCategory'](arg1);
}

export function AddGameToCategory(arg1, arg2) {
  return window['go']['service']['CategoryService']['AddGameToCategory'](arg1, arg2);
}

export function AddGamesToCategories(arg1, arg2) {
  return window['go']['service']['CategoryService']['AddGamesToCategories'](arg1, arg2);
}

export function DeleteCategories(arg1) {
  return window['go']['service']['CategoryService']['DeleteCategories'](arg1);
}

export function DeleteCategory(arg1) {
  return window['go']['service']['CategoryService']['DeleteCategory'](arg1);
}

export function GetCategories() {
  return window['go']['service']['CategoryService']['GetCategories']();
}

export function GetCategoriesByGame(arg1) {
  return window['go']['service']['CategoryService']['GetCategoriesByGame'](arg1);
}

export function GetCategoryByID(arg1) {
  return window['go']['service']['CategoryService']['GetCategoryByID'](arg1);
}

export function GetGamesByCategory(arg1) {
  return window['go']['service']['CategoryService']['GetGamesByCategory'](arg1);
}

export function Init(arg1, arg2, arg3) {
  return window['go']['service']['CategoryService']['Init'](arg1, arg2, arg3);
}

export function RemoveGameFromCategory(arg1, arg2) {
  return window['go']['service']['CategoryService']['RemoveGameFromCategory'](arg1, arg2);
}

export function RemoveGamesFromCategory(arg1, arg2) {
  return window['go']['service']['CategoryService']['RemoveGamesFromCategory'](arg1, arg2);
}

export function UpdateCategory(arg1, arg2) {
  return window['go']['service']['CategoryService']['UpdateCategory'](arg1, arg2);
}
