// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {vo} from '../models';
import {models} from '../models';
import {context} from '../models';
import {sql} from '../models';
import {appconf} from '../models';

export function AddCategory(arg1:string):Promise<void>;

export function AddGameToCategory(arg1:string,arg2:string):Promise<void>;

export function AddGamesToCategories(arg1:Array<string>,arg2:Array<string>):Promise<void>;

export function DeleteCategories(arg1:Array<string>):Promise<void>;

export function DeleteCategory(arg1:string):Promise<void>;

export function GetCategories():Promise<Array<vo.CategoryVO>>;

export function GetCategoriesByGame(arg1:string):Promise<Array<vo.CategoryVO>>;

export function GetCategoryByID(arg1:string):Promise<vo.CategoryVO>;

export function GetGamesByCategory(arg1:string):Promise<Array<models.Game>>;

export function Init(arg1:context.Context,arg2:sql.DB,arg3:appconf.AppConfig):Promise<void>;

export function RemoveGameFromCategory(arg1:string,arg2:string):Promise<void>;

export function RemoveGamesFromCategory(arg1:Array<string>,arg2:string):Promise<void>;

export function UpdateCategory(arg1:string,arg2:string):Promise<void>;
