// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {enums} from '../models';
import {context} from '../models';
import {sql} from '../models';
import {appconf} from '../models';

export function CountCharactors():Promise<number>;

export function CreateCharactor(arg1:models.Charactor):Promise<void>;

export function CreateOrUpdateCharactor(arg1:string,arg2:string,arg3:string,arg4:enums.SourceType,arg5:string,arg6:string,arg7:string):Promise<models.Charactor>;

export function DeleteCharactor(arg1:string):Promise<void>;

export function GetCharactorByGameIdAndName(arg1:string,arg2:string):Promise<models.Charactor>;

export function GetCharactorById(arg1:string):Promise<models.Charactor>;

export function GetCharactorByQueryId(arg1:string,arg2:string,arg3:string):Promise<models.Charactor>;

export function GetCharactorBySource(arg1:enums.SourceType,arg2:string):Promise<models.Charactor>;

export function Init(arg1:context.Context,arg2:sql.DB,arg3:appconf.AppConfig):Promise<void>;

export function ListCharactors():Promise<Array<models.Charactor>>;

export function UpdateCharactor(arg1:models.Charactor):Promise<void>;
