// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CountCharactors() {
  return window['go']['service']['CharactorService']['CountCharactors']();
}

export function CreateCharactor(arg1) {
  return window['go']['service']['CharactorService']['CreateCharactor'](arg1);
}

export function CreateOrUpdateCharactor(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['service']['CharactorService']['CreateOrUpdateCharactor'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function DeleteCharactor(arg1) {
  return window['go']['service']['CharactorService']['DeleteCharactor'](arg1);
}

export function GetCharactorByGameIdAndName(arg1, arg2) {
  return window['go']['service']['CharactorService']['GetCharactorByGameIdAndName'](arg1, arg2);
}

export function GetCharactorById(arg1) {
  return window['go']['service']['CharactorService']['GetCharactorById'](arg1);
}

export function GetCharactorByQueryId(arg1, arg2, arg3) {
  return window['go']['service']['CharactorService']['GetCharactorByQueryId'](arg1, arg2, arg3);
}

export function GetCharactorBySource(arg1, arg2) {
  return window['go']['service']['CharactorService']['GetCharactorBySource'](arg1, arg2);
}

export function Init(arg1, arg2, arg3) {
  return window['go']['service']['CharactorService']['Init'](arg1, arg2, arg3);
}

export function ListCharactors() {
  return window['go']['service']['CharactorService']['ListCharactors']();
}

export function UpdateCharactor(arg1) {
  return window['go']['service']['CharactorService']['UpdateCharactor'](arg1);
}
