// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAppConfig() {
  return window['go']['service']['ConfigService']['GetAppConfig']();
}

export function Init(arg1, arg2, arg3) {
  return window['go']['service']['ConfigService']['Init'](arg1, arg2, arg3);
}

export function SafeQuit() {
  return window['go']['service']['ConfigService']['SafeQuit']();
}

export function SaveCroppedBackgroundImage(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['service']['ConfigService']['SaveCroppedBackgroundImage'](arg1, arg2, arg3, arg4, arg5);
}

export function SelectAndCropBackgroundImage() {
  return window['go']['service']['ConfigService']['SelectAndCropBackgroundImage']();
}

export function SelectBackgroundImage() {
  return window['go']['service']['ConfigService']['SelectBackgroundImage']();
}

export function SetQuitHandler(arg1) {
  return window['go']['service']['ConfigService']['SetQuitHandler'](arg1);
}

export function UpdateAppConfig(arg1) {
  return window['go']['service']['ConfigService']['UpdateAppConfig'](arg1);
}
