// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddGame(arg1) {
  return window['go']['service']['GameService']['AddGame'](arg1);
}

export function DeleteGame(arg1) {
  return window['go']['service']['GameService']['DeleteGame'](arg1);
}

export function ExecueteGamesUpdate(arg1, arg2) {
  return window['go']['service']['GameService']['ExecueteGamesUpdate'](arg1, arg2);
}

export function FetchMetadata(arg1) {
  return window['go']['service']['GameService']['FetchMetadata'](arg1);
}

export function FetchMetadataByName(arg1) {
  return window['go']['service']['GameService']['FetchMetadataByName'](arg1);
}

export function FillGame(arg1, arg2) {
  return window['go']['service']['GameService']['FillGame'](arg1, arg2);
}

export function GetGameByID(arg1) {
  return window['go']['service']['GameService']['GetGameByID'](arg1);
}

export function GetGames() {
  return window['go']['service']['GameService']['GetGames']();
}

export function Init(arg1, arg2, arg3) {
  return window['go']['service']['GameService']['Init'](arg1, arg2, arg3);
}

export function SelectCoverImage(arg1) {
  return window['go']['service']['GameService']['SelectCoverImage'](arg1);
}

export function SelectCoverImageWithTempID() {
  return window['go']['service']['GameService']['SelectCoverImageWithTempID']();
}

export function SelectGameExecutable() {
  return window['go']['service']['GameService']['SelectGameExecutable']();
}

export function SelectSaveDirectory() {
  return window['go']['service']['GameService']['SelectSaveDirectory']();
}

export function SetServices(arg1, arg2, arg3, arg4) {
  return window['go']['service']['GameService']['SetServices'](arg1, arg2, arg3, arg4);
}

export function UpdateGame(arg1) {
  return window['go']['service']['GameService']['UpdateGame'](arg1);
}

export function UpdateGameFromRemote(arg1) {
  return window['go']['service']['GameService']['UpdateGameFromRemote'](arg1);
}

export function UpdateGamesBackground(arg1, arg2, arg3) {
  return window['go']['service']['GameService']['UpdateGamesBackground'](arg1, arg2, arg3);
}
