// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {vo} from '../models';
import {context} from '../models';
import {sql} from '../models';
import {appconf} from '../models';
import {service} from '../models';

export function AddGame(arg1:models.Game):Promise<void>;

export function DeleteGame(arg1:string):Promise<void>;

export function ExecueteGamesUpdate(arg1:Array<models.Game>,arg2:vo.MetadataRequest):Promise<void>;

export function FetchMetadata(arg1:vo.MetadataRequest):Promise<models.Game>;

export function FetchMetadataByName(arg1:string):Promise<Array<vo.GameMetadataFromWebVO>>;

export function FillGame(arg1:models.Game,arg2:models.Game):Promise<void>;

export function GetGameByID(arg1:string):Promise<models.Game>;

export function GetGames():Promise<Array<models.Game>>;

export function Init(arg1:context.Context,arg2:sql.DB,arg3:appconf.AppConfig):Promise<void>;

export function SelectCoverImage(arg1:string):Promise<string>;

export function SelectCoverImageWithTempID():Promise<string>;

export function SelectGameExecutable():Promise<string>;

export function SelectSaveDirectory():Promise<string>;

export function SetServices(arg1:service.TaskService,arg2:service.CharactorService,arg3:service.StaffService,arg4:service.WorkService):Promise<void>;

export function UpdateGame(arg1:models.Game):Promise<void>;

export function UpdateGameFromRemote(arg1:string):Promise<void>;

export function UpdateGamesBackground(arg1:Array<models.Game>,arg2:vo.MetadataRequest,arg3:string):Promise<void>;
