// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddGame(arg1) {
  return window['go']['service']['GameService']['AddGame'](arg1);
}

export function BatchUpdateStatus(arg1, arg2) {
  return window['go']['service']['GameService']['BatchUpdateStatus'](arg1, arg2);
}

export function DeleteGame(arg1) {
  return window['go']['service']['GameService']['DeleteGame'](arg1);
}

export function DeleteGames(arg1) {
  return window['go']['service']['GameService']['DeleteGames'](arg1);
}

export function FetchMetadata(arg1) {
  return window['go']['service']['GameService']['FetchMetadata'](arg1);
}

export function FetchMetadataByName(arg1) {
  return window['go']['service']['GameService']['FetchMetadataByName'](arg1);
}

export function FillGame(arg1, arg2) {
  return window['go']['service']['GameService']['FillGame'](arg1, arg2);
}

export function GetGameByID(arg1) {
  return window['go']['service']['GameService']['GetGameByID'](arg1);
}

export function GetGames() {
  return window['go']['service']['GameService']['GetGames']();
}

export function GetRunningProcesses() {
  return window['go']['service']['GameService']['GetRunningProcesses']();
}

export function Init(arg1, arg2, arg3) {
  return window['go']['service']['GameService']['Init'](arg1, arg2, arg3);
}

export function OpenLocalPath(arg1) {
  return window['go']['service']['GameService']['OpenLocalPath'](arg1);
}

export function SelectCoverImage(arg1) {
  return window['go']['service']['GameService']['SelectCoverImage'](arg1);
}

export function SelectCoverImageWithTempID() {
  return window['go']['service']['GameService']['SelectCoverImageWithTempID']();
}

export function SelectGameExecutable() {
  return window['go']['service']['GameService']['SelectGameExecutable']();
}

export function SelectSaveDirectory() {
  return window['go']['service']['GameService']['SelectSaveDirectory']();
}

export function SelectSaveFile() {
  return window['go']['service']['GameService']['SelectSaveFile']();
}

export function UpdateGame(arg1) {
  return window['go']['service']['GameService']['UpdateGame'](arg1);
}

export function UpdateGameFromRemote(arg1) {
  return window['go']['service']['GameService']['UpdateGameFromRemote'](arg1);
}

export function UpdateGameProcessName(arg1, arg2) {
  return window['go']['service']['GameService']['UpdateGameProcessName'](arg1, arg2);
}
