// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {context} from '../models';
import {sql} from '../models';
import {appconf} from '../models';

export function CountImageBackups():Promise<number>;

export function CreateImageBackup(arg1:models.ImageBackup):Promise<void>;

export function CreateOrUpdateForUrlsStr(arg1:string):Promise<void>;

export function CreateOrUpdateImageBackup(arg1:models.ImageBackup):Promise<void>;

export function CreateOrUpdateImageUrl(arg1:string):Promise<void>;

export function DeleteImageBackup(arg1:string):Promise<void>;

export function GetImageBackupByLocalPath(arg1:string):Promise<models.ImageBackup>;

export function GetImageBackupByUrl(arg1:string):Promise<models.ImageBackup>;

export function GetImageBackupsByUrls(arg1:Array<string>):Promise<Array<models.ImageBackup>>;

export function Init(arg1:context.Context,arg2:sql.DB,arg3:appconf.AppConfig):Promise<void>;

export function ListImageBackups():Promise<Array<models.ImageBackup>>;

export function UpdateImageBackup(arg1:models.ImageBackup):Promise<void>;
