// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CountImageBackups() {
  return window['go']['service']['ImageService']['CountImageBackups']();
}

export function CreateImageBackup(arg1) {
  return window['go']['service']['ImageService']['CreateImageBackup'](arg1);
}

export function CreateOrUpdateForUrlsStr(arg1) {
  return window['go']['service']['ImageService']['CreateOrUpdateForUrlsStr'](arg1);
}

export function CreateOrUpdateImageBackup(arg1) {
  return window['go']['service']['ImageService']['CreateOrUpdateImageBackup'](arg1);
}

export function CreateOrUpdateImageUrl(arg1) {
  return window['go']['service']['ImageService']['CreateOrUpdateImageUrl'](arg1);
}

export function DeleteImageBackup(arg1) {
  return window['go']['service']['ImageService']['DeleteImageBackup'](arg1);
}

export function GetImageBackupByLocalPath(arg1) {
  return window['go']['service']['ImageService']['GetImageBackupByLocalPath'](arg1);
}

export function GetImageBackupByUrl(arg1) {
  return window['go']['service']['ImageService']['GetImageBackupByUrl'](arg1);
}

export function GetImageBackupsByUrls(arg1) {
  return window['go']['service']['ImageService']['GetImageBackupsByUrls'](arg1);
}

export function Init(arg1, arg2, arg3) {
  return window['go']['service']['ImageService']['Init'](arg1, arg2, arg3);
}

export function ListImageBackups() {
  return window['go']['service']['ImageService']['ListImageBackups']();
}

export function UpdateImageBackup(arg1) {
  return window['go']['service']['ImageService']['UpdateImageBackup'](arg1);
}
