// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BatchImportGames(arg1) {
  return window['go']['service']['ImportService']['BatchImportGames'](arg1);
}

export function FetchMetadataForCandidate(arg1) {
  return window['go']['service']['ImportService']['FetchMetadataForCandidate'](arg1);
}

export function ImportFromPlaynite(arg1, arg2) {
  return window['go']['service']['ImportService']['ImportFromPlaynite'](arg1, arg2);
}

export function ImportFromPotatoVN(arg1, arg2) {
  return window['go']['service']['ImportService']['ImportFromPotatoVN'](arg1, arg2);
}

export function Init(arg1, arg2, arg3, arg4) {
  return window['go']['service']['ImportService']['Init'](arg1, arg2, arg3, arg4);
}

export function PreviewImport(arg1) {
  return window['go']['service']['ImportService']['PreviewImport'](arg1);
}

export function PreviewPlayniteImport(arg1) {
  return window['go']['service']['ImportService']['PreviewPlayniteImport'](arg1);
}

export function ProcessDroppedPaths(arg1) {
  return window['go']['service']['ImportService']['ProcessDroppedPaths'](arg1);
}

export function ScanLibraryDirectory(arg1) {
  return window['go']['service']['ImportService']['ScanLibraryDirectory'](arg1);
}

export function SelectJSONFile() {
  return window['go']['service']['ImportService']['SelectJSONFile']();
}

export function SelectLibraryDirectory() {
  return window['go']['service']['ImportService']['SelectLibraryDirectory']();
}

export function SelectZipFile() {
  return window['go']['service']['ImportService']['SelectZipFile']();
}

export function SetSessionService(arg1) {
  return window['go']['service']['ImportService']['SetSessionService'](arg1);
}
