// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {vo} from '../models';
import {service} from '../models';
import {context} from '../models';
import {sql} from '../models';
import {appconf} from '../models';

export function BatchImportGames(arg1:Array<vo.BatchImportCandidate>):Promise<service.ImportResult>;

export function FetchMetadataForCandidate(arg1:string):Promise<vo.BatchImportCandidate>;

export function ImportFromPlaynite(arg1:string,arg2:boolean):Promise<service.ImportResult>;

export function ImportFromPotatoVN(arg1:string,arg2:boolean):Promise<service.ImportResult>;

export function Init(arg1:context.Context,arg2:sql.DB,arg3:appconf.AppConfig,arg4:service.GameService):Promise<void>;

export function PreviewImport(arg1:string):Promise<Array<service.PreviewGame>>;

export function PreviewPlayniteImport(arg1:string):Promise<Array<service.PreviewGame>>;

export function ProcessDroppedPaths(arg1:Array<string>):Promise<Array<vo.BatchImportCandidate>>;

export function ScanLibraryDirectory(arg1:string):Promise<Array<vo.BatchImportCandidate>>;

export function SelectJSONFile():Promise<string>;

export function SelectLibraryDirectory():Promise<string>;

export function SelectZipFile():Promise<string>;

export function SetSessionService(arg1:service.SessionService):Promise<void>;
