// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {time} from '../models';
import {models} from '../models';
import {context} from '../models';
import {sql} from '../models';
import {appconf} from '../models';

export function AddPlaySession(arg1:string,arg2:time.Time,arg3:number):Promise<models.PlaySession>;

export function BatchAddPlaySessions(arg1:Array<models.PlaySession>):Promise<void>;

export function CleanupUnfinishedSessions():Promise<void>;

export function CreatePendingSession(arg1:string,arg2:time.Time):Promise<string>;

export function DeletePlaySession(arg1:string):Promise<void>;

export function GetPlaySessions(arg1:string):Promise<Array<models.PlaySession>>;

export function Init(arg1:context.Context,arg2:sql.DB,arg3:appconf.AppConfig):Promise<void>;

export function UpdatePlaySession(arg1:models.PlaySession):Promise<void>;
