// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddPlaySession(arg1, arg2, arg3) {
  return window['go']['service']['SessionService']['AddPlaySession'](arg1, arg2, arg3);
}

export function BatchAddPlaySessions(arg1) {
  return window['go']['service']['SessionService']['BatchAddPlaySessions'](arg1);
}

export function CleanupUnfinishedSessions() {
  return window['go']['service']['SessionService']['CleanupUnfinishedSessions']();
}

export function CreatePendingSession(arg1, arg2) {
  return window['go']['service']['SessionService']['CreatePendingSession'](arg1, arg2);
}

export function DeletePlaySession(arg1) {
  return window['go']['service']['SessionService']['DeletePlaySession'](arg1);
}

export function GetPlaySessions(arg1) {
  return window['go']['service']['SessionService']['GetPlaySessions'](arg1);
}

export function Init(arg1, arg2, arg3) {
  return window['go']['service']['SessionService']['Init'](arg1, arg2, arg3);
}

export function UpdatePlaySession(arg1) {
  return window['go']['service']['SessionService']['UpdatePlaySession'](arg1);
}
