// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CountStaffs() {
  return window['go']['service']['StaffService']['CountStaffs']();
}

export function CreateOrUpdateStaff(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['service']['StaffService']['CreateOrUpdateStaff'](arg1, arg2, arg3, arg4, arg5);
}

export function CreateStaff(arg1) {
  return window['go']['service']['StaffService']['CreateStaff'](arg1);
}

export function DeleteStaff(arg1) {
  return window['go']['service']['StaffService']['DeleteStaff'](arg1);
}

export function GetFirstStaff() {
  return window['go']['service']['StaffService']['GetFirstStaff']();
}

export function GetStaffByGameIdAndName(arg1, arg2) {
  return window['go']['service']['StaffService']['GetStaffByGameIdAndName'](arg1, arg2);
}

export function GetStaffById(arg1) {
  return window['go']['service']['StaffService']['GetStaffById'](arg1);
}

export function GetStaffByQueryId(arg1, arg2, arg3) {
  return window['go']['service']['StaffService']['GetStaffByQueryId'](arg1, arg2, arg3);
}

export function GetStaffBySource(arg1, arg2) {
  return window['go']['service']['StaffService']['GetStaffBySource'](arg1, arg2);
}

export function GetStaffsByGameId(arg1) {
  return window['go']['service']['StaffService']['GetStaffsByGameId'](arg1);
}

export function Init(arg1, arg2, arg3) {
  return window['go']['service']['StaffService']['Init'](arg1, arg2, arg3);
}

export function ListStaffs() {
  return window['go']['service']['StaffService']['ListStaffs']();
}

export function UpdateStaff(arg1) {
  return window['go']['service']['StaffService']['UpdateStaff'](arg1);
}
