// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {enums} from '../models';
import {models} from '../models';
import {context} from '../models';
import {sql} from '../models';
import {appconf} from '../models';

export function CountStaffs():Promise<number>;

export function CreateOrUpdateStaff(arg1:string,arg2:string,arg3:string,arg4:enums.SourceType,arg5:string):Promise<models.Staff>;

export function CreateStaff(arg1:models.Staff):Promise<void>;

export function DeleteStaff(arg1:string):Promise<void>;

export function GetFirstStaff():Promise<models.Staff>;

export function GetStaffByGameIdAndName(arg1:string,arg2:string):Promise<models.Staff>;

export function GetStaffById(arg1:string):Promise<models.Staff>;

export function GetStaffByQueryId(arg1:string,arg2:string,arg3:string):Promise<models.Staff>;

export function GetStaffBySource(arg1:enums.SourceType,arg2:string):Promise<models.Staff>;

export function GetStaffsByGameId(arg1:string):Promise<Array<models.Staff>>;

export function Init(arg1:context.Context,arg2:sql.DB,arg3:appconf.AppConfig):Promise<void>;

export function ListStaffs():Promise<Array<models.Staff>>;

export function UpdateStaff(arg1:models.Staff):Promise<void>;
