// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';
import {sql} from '../models';
import {appconf} from '../models';
import {service} from '../models';

export function CancelProcessSelection(arg1:string):Promise<void>;

export function CleanupPendingSessions():Promise<void>;

export function Init(arg1:context.Context,arg2:sql.DB,arg3:appconf.AppConfig):Promise<void>;

export function NotifyProcessSelected(arg1:string,arg2:string):Promise<void>;

export function SetBackupService(arg1:service.BackupService):Promise<void>;

export function SetGameService(arg1:service.GameService):Promise<void>;

export function SetSessionService(arg1:service.SessionService):Promise<void>;

export function StartGameWithOptions(arg1:string,arg2:service.LaunchOptions):Promise<boolean>;

export function StartGameWithTracking(arg1:string):Promise<boolean>;
