// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelProcessSelection(arg1) {
  return window['go']['service']['StartService']['CancelProcessSelection'](arg1);
}

export function CleanupPendingSessions() {
  return window['go']['service']['StartService']['CleanupPendingSessions']();
}

export function Init(arg1, arg2, arg3) {
  return window['go']['service']['StartService']['Init'](arg1, arg2, arg3);
}

export function NotifyProcessSelected(arg1, arg2) {
  return window['go']['service']['StartService']['NotifyProcessSelected'](arg1, arg2);
}

export function SetBackupService(arg1) {
  return window['go']['service']['StartService']['SetBackupService'](arg1);
}

export function SetGameService(arg1) {
  return window['go']['service']['StartService']['SetGameService'](arg1);
}

export function SetSessionService(arg1) {
  return window['go']['service']['StartService']['SetSessionService'](arg1);
}

export function StartGameWithOptions(arg1, arg2) {
  return window['go']['service']['StartService']['StartGameWithOptions'](arg1, arg2);
}

export function StartGameWithTracking(arg1) {
  return window['go']['service']['StartService']['StartGameWithTracking'](arg1);
}
