// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CountTags() {
  return window['go']['service']['TagService']['CountTags']();
}

export function CreateOrUpdateTag(arg1, arg2) {
  return window['go']['service']['TagService']['CreateOrUpdateTag'](arg1, arg2);
}

export function CreateOrUpdateTagMapArray(arg1) {
  return window['go']['service']['TagService']['CreateOrUpdateTagMapArray'](arg1);
}

export function CreateTag(arg1) {
  return window['go']['service']['TagService']['CreateTag'](arg1);
}

export function DeleteTag(arg1) {
  return window['go']['service']['TagService']['DeleteTag'](arg1);
}

export function GetTagByName(arg1) {
  return window['go']['service']['TagService']['GetTagByName'](arg1);
}

export function GetTagListByString(arg1) {
  return window['go']['service']['TagService']['GetTagListByString'](arg1);
}

export function GetTagMap() {
  return window['go']['service']['TagService']['GetTagMap']();
}

export function GetTagsMapByString(arg1) {
  return window['go']['service']['TagService']['GetTagsMapByString'](arg1);
}

export function Init(arg1, arg2, arg3) {
  return window['go']['service']['TagService']['Init'](arg1, arg2, arg3);
}

export function ListTags() {
  return window['go']['service']['TagService']['ListTags']();
}

export function UpdateTag(arg1) {
  return window['go']['service']['TagService']['UpdateTag'](arg1);
}
