// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {context} from '../models';
import {sql} from '../models';
import {appconf} from '../models';

export function CountTags():Promise<number>;

export function CreateOrUpdateTag(arg1:string,arg2:string):Promise<void>;

export function CreateOrUpdateTagMapArray(arg1:Record<string, Array<string>>):Promise<void>;

export function CreateTag(arg1:models.Tag):Promise<void>;

export function DeleteTag(arg1:string):Promise<void>;

export function GetTagByName(arg1:string):Promise<models.Tag>;

export function GetTagListByString(arg1:string):Promise<Array<models.Tag>>;

export function GetTagMap():Promise<Record<string, Array<string>>>;

export function GetTagsMapByString(arg1:string):Promise<Record<string, Array<models.Tag>>>;

export function Init(arg1:context.Context,arg2:sql.DB,arg3:appconf.AppConfig):Promise<void>;

export function ListTags():Promise<Array<models.Tag>>;

export function UpdateTag(arg1:models.Tag):Promise<void>;
