// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelTask(arg1) {
  return window['go']['service']['TaskService']['CancelTask'](arg1);
}

export function Close() {
  return window['go']['service']['TaskService']['Close']();
}

export function GetActiveTask() {
  return window['go']['service']['TaskService']['GetActiveTask']();
}

export function GetTaskNotice(arg1) {
  return window['go']['service']['TaskService']['GetTaskNotice'](arg1);
}

export function Init(arg1, arg2, arg3) {
  return window['go']['service']['TaskService']['Init'](arg1, arg2, arg3);
}

export function PauseTask(arg1) {
  return window['go']['service']['TaskService']['PauseTask'](arg1);
}

export function RegisterTaskFunction(arg1, arg2) {
  return window['go']['service']['TaskService']['RegisterTaskFunction'](arg1, arg2);
}

export function ResumeTask(arg1) {
  return window['go']['service']['TaskService']['ResumeTask'](arg1);
}

export function StartTask(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['service']['TaskService']['StartTask'](arg1, arg2, arg3, arg4, arg5, arg6);
}
