// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {context} from '../models';
import {sql} from '../models';
import {appconf} from '../models';
import {service} from '../models';
import {enums} from '../models';

export function CancelTask(arg1:string):Promise<void>;

export function Close():Promise<void>;

export function GetActiveTask():Promise<models.Task>;

export function GetTaskNotice(arg1:models.Task):Promise<models.TaskNotice>;

export function Init(arg1:context.Context,arg2:sql.DB,arg3:appconf.AppConfig):Promise<void>;

export function PauseTask(arg1:string):Promise<void>;

export function RegisterTaskFunction(arg1:string,arg2:service.TaskFunction):Promise<void>;

export function ResumeTask(arg1:string):Promise<void>;

export function StartTask(arg1:string,arg2:string,arg3:number,arg4:enums.TaskType,arg5:number,arg6:any):Promise<void>;
