// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CountWorks() {
  return window['go']['service']['WorkService']['CountWorks']();
}

export function CreateOrUpdateListWorkStaffCharactor(arg1) {
  return window['go']['service']['WorkService']['CreateOrUpdateListWorkStaffCharactor'](arg1);
}

export function CreateOrUpdateWorkStaffCharactor(arg1) {
  return window['go']['service']['WorkService']['CreateOrUpdateWorkStaffCharactor'](arg1);
}

export function CreateWork(arg1) {
  return window['go']['service']['WorkService']['CreateWork'](arg1);
}

export function GetWorkByCharactor(arg1, arg2) {
  return window['go']['service']['WorkService']['GetWorkByCharactor'](arg1, arg2);
}

export function GetWorkByQueryIds(arg1, arg2, arg3) {
  return window['go']['service']['WorkService']['GetWorkByQueryIds'](arg1, arg2, arg3);
}

export function GetWorkByStaff(arg1, arg2) {
  return window['go']['service']['WorkService']['GetWorkByStaff'](arg1, arg2);
}

export function GetWorksByGameId(arg1) {
  return window['go']['service']['WorkService']['GetWorksByGameId'](arg1);
}

export function GetWorksMapByGameId(arg1) {
  return window['go']['service']['WorkService']['GetWorksMapByGameId'](arg1);
}

export function Init(arg1, arg2, arg3) {
  return window['go']['service']['WorkService']['Init'](arg1, arg2, arg3);
}

export function ListWorks() {
  return window['go']['service']['WorkService']['ListWorks']();
}

export function SetStaffCharactorService(arg1, arg2) {
  return window['go']['service']['WorkService']['SetStaffCharactorService'](arg1, arg2);
}

export function UpdateWork(arg1) {
  return window['go']['service']['WorkService']['UpdateWork'](arg1);
}
