// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {enums} from '../models';
import {context} from '../models';
import {sql} from '../models';
import {appconf} from '../models';
import {service} from '../models';

export function CountWorks():Promise<number>;

export function CreateOrUpdateListWorkStaffCharactor(arg1:Array<models.Work>):Promise<void>;

export function CreateOrUpdateWorkStaffCharactor(arg1:models.Work):Promise<void>;

export function CreateWork(arg1:models.Work):Promise<void>;

export function GetWorkByCharactor(arg1:string,arg2:string):Promise<models.Work>;

export function GetWorkByQueryIds(arg1:string,arg2:string,arg3:string):Promise<models.Work>;

export function GetWorkByStaff(arg1:string,arg2:string):Promise<models.Work>;

export function GetWorksByGameId(arg1:string):Promise<Array<models.Work>>;

export function GetWorksMapByGameId(arg1:string):Promise<Record<enums.StaffRole, Array<models.Work>>>;

export function Init(arg1:context.Context,arg2:sql.DB,arg3:appconf.AppConfig):Promise<void>;

export function ListWorks():Promise<Array<models.Work>>;

export function SetStaffCharactorService(arg1:service.StaffService,arg2:service.CharactorService):Promise<void>;

export function UpdateWork(arg1:models.Work):Promise<void>;
